### ISSUE TITLE
sprocketsによるデプロイエラーを解消する

### ISSUE THREAD

**Issue by R-Tsukada** [R-Tsukada/football-myteam#360]
```
Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v1.22.19
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       warning " > mini-css-extract-plugin@2.9.0" has unmet peer dependency "webpack@^5.0.0".
       warning " > ts-loader@9.5.1" has unmet peer dependency "webpack@^5.0.0".
       warning " > vite-plugin-pwa@0.20.1" has unmet peer dependency "workbox-build@^7.1.0".
       warning " > vite-plugin-pwa@0.20.1" has unmet peer dependency "workbox-window@^7.1.0".
       warning "vite-plugin-pwa > workbox-build > @rollup/plugin-babel@5.3.1" has incorrect peer dependency "rollup@^1.20.0||^2.0.0".
       warning "vite-plugin-pwa > workbox-build > @rollup/plugin-replace@2.4.2" has incorrect peer dependency "rollup@^1.20.0 || ^2.0.0".
       warning "vite-plugin-pwa > workbox-build > @rollup/plugin-babel > @rollup/pluginutils@3.1.0" has incorrect peer dependency "rollup@^1.20.0||^2.0.0".
       warning " > style-loader@4.0.0" has unmet peer dependency "webpack@^5.27.0".
       [4/4] Building fresh packages...
       Done in 47.72s.
       yarn run v1.22.19
       $ bin/vite build --clear --mode=development
       Removed vite cache and output dirs:
       	/tmp/build_ce5e1240/public/vite
       	/tmp/build_ce5e1240/public/vite-ssr
       	/tmp/build_ce5e1240/tmp/cache/vite
       	/tmp/build_ce5e1240/node_modules/.vite
       Building with Vite ⚡️
       $ /tmp/build_ce5e1240/node_modules/.bin/vite build --mode production
       vite v5.4.1 building for production...
       transforming...
       ✓ 120 modules transformed.
       rendering chunks...
       computing gzip size...
       ../../public/vite/.vite/manifest-assets.json              0.00 kB │ gzip:  0.02 kB
       ../../public/vite/.vite/manifest.json                     2.55 kB │ gzip:  0.36 kB
       ../../public/vite/assets/fa-v4compatibility.woff2         4.80 kB
       ../../public/vite/assets/fa-v4compatibility.ttf          10.84 kB
       ../../public/vite/assets/fa-regular-400.woff2            25.46 kB
       ../../public/vite/assets/fa-regular-400.ttf              67.98 kB
       ../../public/vite/assets/fa-brands-400.woff2            118.07 kB
       ../../public/vite/assets/fa-solid-900.woff2             157.19 kB
       ../../public/vite/assets/fa-brands-400.ttf              209.38 kB
       ../../public/vite/assets/fa-solid-900.ttf               423.68 kB
       ../../public/vite/assets/application.css                  0.03 kB │ gzip:  0.05 kB
       ../../public/vite/assets/entrypoints/application.css    309.05 kB │ gzip: 51.96 kB
       ../../public/vite/assets/entrypoints/application.js.js  256.33 kB │ gzip: 87.68 kB │ map: 1,329.14 kB
       ✓ built in 4.17s
       Build with Vite complete: /tmp/build_ce5e1240/public/vite
       DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
       rules will be changing to match the behavior specified by CSS in an upcoming
       version. To keep the existing behavior, move the declaration above the nested
       rule. To opt into the new behavior, wrap the declaration in `& {}`.
       
       More info: https://sass-lang.com/d/mixed-decls
       
          ╷
       51 │ ┌   &:not(.is-rounded)
       52 │ │     border-radius: $radius-small
          │ └─── nested rule
       53 │     font-size: $size-small
          │     ^^^^^^^^^^^^^^^^^^^^^^ declaration
          ╵
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/elements/button.sass 53:3   button-small()
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/elements/button.sass 252:5  @import
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/elements/_all.sass 5:9      @import
           file:///tmp/build_ce5e1240/node_modules/bulma/bulma.sass 5:9                   @import
           file:///tmp/build_ce5e1240/app/javascript/entrypoints/application.scss 1:9     root stylesheet
       
       DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
       rules will be changing to match the behavior specified by CSS in an upcoming
       version. To keep the existing behavior, move the declaration above the nested
       rule. To opt into the new behavior, wrap the declaration in `& {}`.
       
       More info: https://sass-lang.com/d/mixed-decls
       
          ╷
       51 │ ┌   &:not(.is-rounded)
       52 │ │     border-radius: $radius-small
          │ └─── nested rule
       53 │     font-size: $size-small
          │     ^^^^^^^^^^^^^^^^^^^^^^ declaration
          ╵
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/elements/button.sass 53:3   button-small()
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/elements/button.sass 303:7  @import
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/elements/_all.sass 5:9      @import
           file:///tmp/build_ce5e1240/node_modules/bulma/bulma.sass 5:9                   @import
           file:///tmp/build_ce5e1240/app/javascript/entrypoints/application.scss 1:9     root stylesheet
       
       DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
       rules will be changing to match the behavior specified by CSS in an upcoming
       version. To keep the existing behavior, move the declaration above the nested
       rule. To opt into the new behavior, wrap the declaration in `& {}`.
       
       More info: https://sass-lang.com/d/mixed-decls
       
           ╷
       64  │ ┌       &:nth-child(3)
       65  │ │         transform: translateY(-5px) rotate(-45deg)
           │ └─── nested rule
       ... │
       181 │       #{$property}-#{$normal}: $spacing
           │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
           ╵
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/utilities/mixins.sass 181:5   ltr-property()
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/components/navbar.sass 159:3  @import
           file:///tmp/build_ce5e1240/node_modules/bulma/sass/components/_all.sass 12:9     @import
           file:///tmp/build_ce5e1240/node_modules/bulma/bulma.sass 7:9                     @import
           file:///tmp/build_ce5e1240/app/javascript/entrypoints/application.scss 1:9       root stylesheet
       
       
       ../images/first-view-image.png referenced in ../images/first-view-image.png didn't resolve at build time, it will remain unchanged to be resolved at runtime
       
       Done in 8.03s.
       rake aborted!
       Sprockets::ArgumentError: link_directory argument must be a directory (Sprockets::ArgumentError)
       /tmp/build_ce5e1240/app/assets/config/manifest.js:2
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:407:in `expand_relative_dirname'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:343:in `process_link_directory_directive'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:189:in `block in process_directives'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:187:in `each'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:187:in `process_directives'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:84:in `_call'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/directive_processor.rb:65:in `call'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:184:in `load_from_unloaded'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/bundle.rb:27:in `call'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:184:in `load_from_unloaded'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:81:in `find_asset'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:88:in `find_all_linked_assets'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `each'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `to_a'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
       /tmp/build_ce5e1240/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)

 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by R-Tsukada** [comment]
対応が完了したためクローズする
